### ISSUE TITLE
Preflight tests assume role is being run on localhost

### ISSUE THREAD

**Issue by dragon2611** [AbuseIO/abuseio-ansible#1]
The DNS tests fail if you attempt to deploy on a remote ubuntu host.

Particularly as it will install the python modules on the remote host but they're needed on the local machine, I also suspect it's doing the DNS lookup test on the local machine instead of the remote host.

The machine running the playbook shouldn't need to be the one that the role is being deployed on.

**Comment by kruisdraad** [comment]
yes, however the preflight is required to prevent people from installing on a system thats not ready (e.g. missing DNS, etc). If you want to do a remote install, you will need to find a way to make preflight work remotely.
