### ISSUE TITLE
ERROR! 'static' is not a valid attribute for a TaskInclude

### ISSUE THREAD

**Issue by edvinmolla** [AbuseIO/abuseio-ansible#5]
ERROR! 'static' is not a valid attribute for a TaskInclude

The error appears to be in '/opt/abuseio-ansible/roles/apache/tasks/main.yml': line 16, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

"I have changed the IP allowed to just one IP with a prefix : "192.168.1.7/24""

**Comment by pettai** [comment]
I didn't change anything, and I get this error too...

**Comment by kruisdraad** [comment]
It looks like the ansble does not work with the latest version of the script. Some modifications have to be made. Ill have a look when i got time.

**Comment by pettai** [comment]
yes, I get a lot of errors then trying to fix the issues along the way... do you want me to put the things here?

**Comment by kruisdraad** [comment]
i just accepted a PR, that might help.

**Comment by kruisdraad** [comment]
i suggest you try and then submit a PR for testing

**Comment by pettai** [comment]
It's better, but not enough for then I use the [oneshot](https://github.com/AbuseIO/abuseio-ansible#oneshot-installation) install on Debian/Ubuntu

But I'm on my way to make it work (for Debian/Ubuntu) and I could send a PR with my updates

**Comment by pettai** [comment]
But you could close this Issue though

**Comment by edvinmolla** [comment]
Ok, thanks
