### ISSUE TITLE
modernising ansible playbooks 

### ISSUE THREAD

**Issue by pettai** [AbuseIO/abuseio-ansible#8]
In relation to updating to more recent ansible (https://github.com/AbuseIO/abuseio-ansible/issues/5) There are more things that needs fixing for a oneshot install on Ubuntu 16.04.

Here's a PR https://github.com/AbuseIO/abuseio-ansible/pull/7 that fixes installation of all packages for Ubuntu 16.04

**Comment by kruisdraad** [comment]
approved
